version: "3.8"
services:
  sb-app:
    build: .
    container_name: "docker-app"
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data: